[package]
name = "faster-beamer"
version = "0.1.0"
authors = ["Stephan Seitz <stephan.seitz@fau.de>"]
edition = "2018"
description = "An incremental compiler for LaTeX Beamer slides"
license="GPLv3"

[dependencies]
tree-sitter = "0.3.7"
tera = "0.11"
serde_json = "1.0.38"
dirs = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.2.0"
clap = "2.32.0"
hotwatch = "0.3.1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
pretty_env_logger = "0.3.0"
#tectonic = "0.1.11"
latexcompile = "0.1.0"
lopdf = "0.20.0"
cachedir = "0.1.1"
md5 = "0.6.1"
rayon = "1.0.3"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
